language: node_js
node_js:
  - 14  # Use Node.js 14 or newer for better compatibility
cache: npm

services:
  - docker  # Enable Docker service in Travis CI

before_install:
  - docker --version  # Check Docker version for debugging
install:
  - npm install
  - npm run test -- --coverage

script:
  - npm run build  # Build the application

after_success:
  # Report test coverage to Codecov
  - CODECOV_TOKEN=$codecov_token npm run report-coverage

  # Authenticate Docker with Docker Hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  
  # Build Docker image using the Dockerfile
  - docker build -t yineng2002/react-app:$TRAVIS_COMMIT .
  
  # Push Docker image to Docker Hub
  - docker push yineng2002/react-app:$TRAVIS_COMMIT

  # Optional: Run the Docker container (for testing purposes)
  - docker run -p 3000:3000 yineng2002/react-app:$TRAVIS_COMMIT
  
after_script:
  # Report to Coveralls
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Use the correct environment variable here
  local_dir: build
  on:
    branch: master
